# Generated by Django 2.0.4 on 2018-04-25 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Hashtag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='state',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='state',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
