# Generated by Django 2.0.4 on 2018-04-26 08:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0002_auto_20180425_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.CharField(max_length=250)),
                ('date_create', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('date_publish', models.DateField(default=datetime.date.today)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clown.Author')),
                ('hashtag', models.ManyToManyField(help_text='Select a Hashtag for Post', to='clown.Hashtag')),
            ],
            options={
                'ordering': ['date_create'],
            },
        ),
    ]
