# Generated by Django 2.0.4 on 2018-04-26 11:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0006_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
