# Generated by Django 2.0.4 on 2018-05-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0008_author_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
