# Generated by Django 2.0.4 on 2018-05-02 13:57

import clown.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0010_auto_20180502_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_publish']},
        ),
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(height_field='height_field', upload_to=clown.models.upload_location, width_field='width_field'),
        ),
    ]
