# Generated by Django 2.0.4 on 2018-05-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0011_auto_20180502_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
