# Generated by Django 2.0.4 on 2018-05-02 14:11

import clown.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0013_auto_20180502_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=2, height_field='height_field', upload_to=clown.models.upload_location, width_field='width_field'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
