# Generated by Django 2.0.4 on 2018-05-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0015_remove_post_imageold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_publish']},
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(max_length=2500),
        ),
    ]
