# Generated by Django 2.0.4 on 2018-05-03 13:12

import clown.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0017_auto_20180503_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, height_field='height_field', null=True, upload_to=clown.models.upload_location_photo, width_field='width_field'),
        ),
    ]
