# Generated by Django 2.0.4 on 2018-05-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clown', '0018_auto_20180503_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='author',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='author',
            name='width_field',
        ),
    ]
